### ISSUE TITLE
Reconsider using ronn/hpricot

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/facter#2766] opened 2024-10-03 12:42 UTC
## Use Case

I noticed that the Gemfile lists ronn:

* https://rubygems.org/gems/ronn - last released in 2010, the source code link is dead and rubygems doesn't know a license and a dead source code link
* https://rubygems.org/gems/hpricot is a dependency of ronn - last released in 2012, also without a license on rubygems and a dead source code link

I know that ronn is only used for documentation stuff and not a runtime dependency. But still it looks like a potential attack vector.

## Describe the Solution You Would Like

Depend on maintained libraries with a clear license.

**Comment by joshcooper** [comment] 2024-10-03 18:12
Duplicate of https://github.com/puppetlabs/facter/issues/2703

**Closed by joshcooper** 2024-10-03 18:12 UTC
Labels: enhancement
