### ISSUE TITLE
Facter still tries to access EC2 metadata service with EC2 in the blocklist

### ISSUE THREAD

**Issue by robert-cam** [puppetlabs/facter#2672] opened 2024-01-18 10:07 UTC
We're not running in a cloud environment and don't want or need facter to hit metadata services. The docs say adding EC2 will prevent the facts being resolved but facter still tries to access the metadata services.

Testing with facter 4.2.8 on CentOS 7.9 and AlmaLinux 8.9.

**Comment by joshcooper** [comment] 2024-01-23 21:56
@robert-cam can you try with facter 4.5.2 and include the output of `facter --debug` (and sanitize any sensitive data)

**Comment by robert-cam** [comment] 2024-01-24 12:00
[facter-debug.txt](https://github.com/puppetlabs/facter/files/14037801/facter-debug.txt)

**Comment by joshcooper** [comment] 2024-01-24 17:41
```
[2024-01-24 11:22:32.497992 ] DEBUG Facter::Core::Execution::Posix - Executing command: virt-what
[2024-01-24 11:22:32.499457 ] DEBUG Facter::Core::Execution::Posix - Failed while executing 'virt-what': No such file or directory - virt-what
[2024-01-24 11:22:32.499784 ] DEBUG Facter::Core::Execution::Posix - Executing command: lspci
[2024-01-24 11:22:32.517611 ] DEBUG Facts::Linux::Hypervisors::Vmware - No Vmware hypervisor detected.
...
[2024-01-24 11:22:32.518215 ] DEBUG Facter::Core::Execution::Posix - Executing command: vmware -v
[2024-01-24 11:22:32.519675 ] DEBUG Facter::Core::Execution::Posix - Failed while executing 'vmware -v': No such file or directory - vmware
[2024-01-24 11:22:32.519825 ] DEBUG Facter::Core::Execution::Posix - Executing command: virt-what
[2024-01-24 11:22:32.521189 ] DEBUG Facter::Core::Execution::Posix - Failed while executing 'virt-what': No such file or directory - virt-what
[2024-01-24 11:22:32.521600 ] DEBUG Facter::Util::FileHelper - File at: /proc/xen/capabilities is not accessible.
[2024-01-24 11:22:32.521709 ] DEBUG Facter::Core::Execution::Posix - Executing command: ["/usr/sbin/xl", "/usr/sbin/xm"] list
[2024-01-24 11:22:32.523998 ] DEBUG Facter::Resolvers::Xen - Command ["/usr/sbin/xl", "/usr/sbin/xm"] list completed with the following stderr message: sh: [/usr/sbin/xl,: No such file or directory
[2024-01-24 11:22:32.524088 ] DEBUG Facts::Linux::Hypervisors::Xen - No Xen hypervisor detected.
...
[2024-01-24 11:22:32.593064 ] DEBUG Facts::Linux::Virtual - Linux Virtual Resolver
[2024-01-24 11:22:32.593103 ] DEBUG Facts::Linux::Virtual - Fact value is: kvm
...
[2024-01-24 11:22:33.068586 ] DEBUG Facter::Resolvers::Ec2 - Querying Ec2 metadata
[2024-01-24 11:22:33.688348 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/api/token but got: execution expired
```

**Comment by lemkep** [comment] 2024-02-05 15:45
Hi. I'm on Debian bookworm with facter 4.5.2 and blocklist does not work for me, too:
```
# facter --version
4.5.2
# grep mountpoints facter.stderr | cut -c-140
[2024-02-05 16:22:32.529530 ] DEBUG Facter - blocking collection of mountpoints facts 
[2024-02-05 16:22:39.751844 ] DEBUG Facter::FactManager - fact "mountpoints" has resolved to: {"/dev"=>{"device"=>"udev", "filesystem"=
```

**Comment by joshcooper** [comment] 2024-02-08 18:46
@robert-cam @lemkep Could you try installing earlier puppet-agent/facter versions to see if this is a regression?

**Comment by robert-cam** [comment] 2024-02-09 10:11
This happens with facter 4.0.52 from the puppet-agent 7.5.0 package:
```
# facter  --debug 2>&1 |egrep '(EC2|http)'
[2024-02-09 10:07:09.140796 ] DEBUG Facter - blocking collection of EC2 az_metadata facts 
[2024-02-09 10:07:09.507029 ] DEBUG Facter::Util::Resolvers::Http - Request to http://169.254.169.254/metadata/instance?api-version=2020-09-01 failed with error code 403 
# facter -v
4.0.52
```
Doesn't happen with facter 4.0.51 from the puppet-agent 7.4.1 package:
```
# facter  --debug 2>&1 |egrep '(EC2|http)'
[2024-02-09 10:09:51.123153 ] DEBUG Facter - blocking collection of EC2 az_metadata facts 
# facter -v
4.0.51
```

**Comment by lemkep** [comment] 2024-02-09 13:47
Seems to be a different issue for me. It is just the case when using puppet libs with '-p', also with an older versions (tested back until 4.2.10).

Without blocklist:
```
# facter --debug |& egrep "version:|mountpoints" | cut -c -120
[2024-02-09 14:15:30.142853 ] DEBUG Facter - Facter version: 4.4.1
[2024-02-09 14:15:30.646989 ] DEBUG Facter::FactManager - fact "mountpoints" has resolved to: {"/dev"=>{"device"=>"
mountpoints => {
#
```
With blocklist (blocks):
```
# facter --debug -c facter.conf |& egrep "version:|mountpoints" | cut -c -120
[2024-02-09 14:15:48.510386 ] DEBUG Facter - Facter version: 4.4.1 
[2024-02-09 14:15:48.510416 ] DEBUG Facter - blocking collection of mountpoints facts
#
```
With blocklist and '-p':
```
# facter --debug -p -c facter.conf |& egrep "version:|mountpoints" | cut -c -120
[2024-02-09 14:13:14.748915 ] DEBUG Facter - Facter version: 4.4.1 
[2024-02-09 14:13:14.748946 ] DEBUG Facter - blocking collection of mountpoints facts
[2024-02-09 14:13:21.819326 ] DEBUG Facter::FactManager - fact "mountpoints" has resolved to: {"/dev"=>{"device"=>"
mountpoints => {
#
```

**Comment by tvpartytonight** [comment] 2024-03-01 23:12
@robert-cam could your provide what your facter config file looks like? thanks!

**Comment by tvpartytonight** [comment] 2024-03-04 21:02
@robert-cam in your example of the issue happening in the `7.5.0` puppet-agent package, that http request is actually coming from the [azure resolver](https://github.com/puppetlabs/facter/blob/0d2dcdb/lib/facter/resolvers/az.rb#L8), not the EC2 resolver. It looks like you were already trying to block `az_metadata` in your examples earlier in this thread. Based upon the fragments of this thread, maybe blocking azure_metadata is not working? I haven't been able to reproduce any failures to block the EC2 metadata, but I haven't been looking into blocking azure data.

**Comment by robert-cam** [comment] 2024-03-05 09:20
Apologies, I was testing on 2 different VMs and one has this config:
```
facts : {
    blocklist : [ "EC2", "az_metadata" ],
}
```
I've updated and they both have the same facter.conf now.

I've checked and the VM I was using to test all the different facter versions was configured to block az_metadata.

**Comment by tvpartytonight** [comment] 2024-03-09 00:40
@robert-cam I am going to make the assumption that there is no breakage like you described above between facter versions `4.0.51` and `4.0.52`, based upon our `az_metadata` conversation. However, I am still investigating the EC2 issue you are seeing, but have had no luck reproducing it. I put up a branch on my fork of `facter` here: https://github.com/tvpartytonight/facter/tree/add_block_filtering_debug_comments

Do you think that you could run facter from that branch in your VM and share the debug output? You may have to do some installation of packages to allow for `bundle install` to work correctly; I outlined some [steps](https://gist.github.com/tvpartytonight/2a3b5dcb27faa935ecb25822fb167dd8) here which should be what is neccesary to run facter from git in your VM.

**Comment by robert-cam** [comment] 2024-03-11 11:03
@tvpartytonight here's the debug output with your fork:
```
# bundle exec facter --debug -p 2>&1 | egrep -i "(EC2|aws|http)"
[2024-03-11 11:00:06.884102 ] DEBUG Facter - blocking collection of EC2 az_metadata facts 
[2024-03-11 11:00:06.936254 ] DEBUG Facter::Resolvers::Ec2 - Querying Ec2 metadata 
[2024-03-11 11:00:16.975009 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/api/token but got: Net::ReadTimeout with #<Socket:(closed)> 
[2024-03-11 11:00:26.993533 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/meta-data/ but got: Net::ReadTimeout with #<Socket:(closed)> 
[2024-03-11 11:00:37.016814 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/user-data/ but got: Net::ReadTimeout with #<Socket:(closed)> 
# bundle exec facter --version
4.6.1
# facter virtual
kvm
```

**Comment by tvpartytonight** [comment] 2024-03-11 16:21
Ahh, sorry @robert-cam I accidentally left my changes on my local fork; can you try again? We are looking for the debug statements that are added here: https://github.com/puppetlabs/facter/compare/main...tvpartytonight:facter:add_block_filtering_debug_comments

**Comment by tvpartytonight** [comment] 2024-03-11 22:45
@robert-cam I realize I made a mistake in that branch which I have now fixed; would you mind fetching the latest for that branch and retrying?

**Comment by robert-cam** [comment] 2024-03-12 11:06
@tvpartytonight sure, see attached. 
[debug.txt](https://github.com/puppetlabs/facter/files/14571258/debug.txt)

**Comment by tvpartytonight** [comment] 2024-03-12 19:05
Ok @robert-cam AFAICT there's nothing wrong with the blocking of facts happening; I added some more debug about the resolution of `searched_facts` in the branch; can you pull in the changes and share the debug output again?

**Comment by robert-cam** [comment] 2024-03-13 10:25
@tvpartytonight done, see attached.
[debug.txt](https://github.com/puppetlabs/facter/files/14586189/debug.txt)
Thanks for looking, it's much appreciated!

**Comment by tvpartytonight** [comment] 2024-03-13 16:41
@robert-cam can you run a test for me on the main branch of `puppetlabs/facter`? I'd like you to add `cloud.provider` to the list of facts to block, and see if that eliminates the calls to ec2 during facter execution.

**Comment by tvpartytonight** [comment] 2024-03-19 21:37
@robert-cam I opened up #2690 to track what I think is really the issue here; I'm going to close this issue out as I think that your issue can be resolved by further blocking the `cloud.provider` fact. Please let me know if you have any further questions.

**Closed by tvpartytonight** 2024-03-19 21:37 UTC
Labels: triaged, bug

**Comment by robert-cam** [comment] 2024-03-25 11:21
Confirmed, blocking cloud.provider works for me. Thanks!

**Comment by jan-matejka** [comment] 2025-11-14 11:36
```
# facter -d 2>&1 | grep  'EC\|Ec2' -A 4
[2025-11-14 12:33:34.504892 ] DEBUG Facter - blocking collection of EC2 facts 
[2025-11-14 12:33:34.506828 ] DEBUG Facter::FactManager - Resolving facts sequentially 
[2025-11-14 12:33:34.507223 ] DEBUG Facter::FactLoader - Loading all internal facts 
[2025-11-14 12:33:34.516847 ] DEBUG Facter::FactLoader - Loading custom facts 
[2025-11-14 12:33:34.518068 ] DEBUG Facter::FactLoader - Loading external facts 
--
[2025-11-14 12:33:34.759816 ] DEBUG Facter::Resolvers::Ec2 - Querying Ec2 metadata 
[2025-11-14 12:33:35.404248 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/api/token but got: Failed to open TCP connection to 169.254.169.254:80 (execution expired) 
[2025-11-14 12:33:36.005867 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/meta-data/ but got: Failed to open TCP connection to 169.254.169.254:80 (execution expired) 
[2025-11-14 12:33:36.607497 ] DEBUG Facter::Util::Resolvers::Http - Trying to connect to http://169.254.169.254/latest/user-data/ but got: Failed to open TCP connection to 169.254.169.254:80 (execution expired) 
```

current trixie facter/stable,now 4.10.0-1 all [installed,automatic]

work around by blocking cloud.provider works.
